### PR TITLE
Datamesh

### PR DESCRIPTION
**Pull request by rafa-guedes**
@tomdurrant this is a first cut for implementing a Datamesh reader for the Data classes.

Main code is [here](https://github.com/oceanum/rompy/blob/datamesh/rompy/core/data.py#L120)
Testing is [here](https://github.com/oceanum/rompy/blob/datamesh/tests/test_data.py#L144-L148)
Notebook example is [here](https://github.com/oceanum/rompy/blob/datamesh/notebooks/oceanum_example_datamesh.ipynb)
Config for the notebook is [here](https://github.com/oceanum/rompy/blob/datamesh/notebooks/oceanum_datamesh_demo.yml#L34-L37)

The `open()` method in the new `DatasetDatamesh` reader class currently uses the `load_datasource` connector method. This is not ideal and we should change it to use `query` instead so that slicing happens on the server side and the data are cached. However the current api of `DataGrid` expects the reader to return the xarray Dataset object in the open() method and the slicing takes place inside `DataGrid.ds` by the filters, after the `open()` has been called. We should rethink this approach to try and make it more flexible.

### CODE REVIEW

**Comment by rafa-guedes** [comment]
@tomdurrant I have implement a few sensitive changes to the core Data objects to address the issue raised above. Please review this when you have a chance and see what you think. There are a couple of breaking changes to both the `Dataset` reader and the `DataGrid` objects.

### Dataset readers

- Previously `rompy.core.data.Dataset` was an abstract class implementing the Dataset reader api, with basically only the `open()` method that needed to be overridden by the subclasses `DatasetXarray`, `DatasetIntake`, etc to return an `xr.Dataset` object. Here, [Dataset](https://github.com/oceanum/rompy/blob/datamesh/rompy/core/data.py#L71)` was turned into a base class that can be used by providing an existing xarray Dataset object as the `dataset` argument. This addresses one of the concerns raised during the workshop where the user may want to work on a Notebook for example, do some custom processing to an existing Dataset and use it in rompy directly without having to save as a netcdf file and then use one of the available Dataset readers.

- The `Dataset` class is still expected to define a base class to define the api for all other Dataset subclasses. However since it now has the `dataset` argument (which receives an xarray dataset object), the subclasses need to override this argument. The idea here is that each subclass reader will use this argument `dataset` to to prescribe the main parameter to construct the xr.Dataset obj. i.e.:
  - In the case of `DatasetXarray`, the [dataset](https://github.com/oceanum/rompy/blob/datamesh/rompy/core/data.py#L136) argument now replaces the deprecated `path` argument to specify the file path.
  - In the case of `DatasetIntake`, the [dataset](https://github.com/oceanum/rompy/blob/datamesh/rompy/core/data.py#L160-L162) argument now replaces the depracated `dataset_id` argument specifying id of the dataset in the catalog.
  - In the case of `DatasetDatamesh`, the [dataset](https://github.com/oceanum/rompy/blob/datamesh/rompy/core/data.py#L200-L202) argument now replaces the deprecated `dataset_id` argument specifying the datasource id.

- The `open()` method now receives `variables` and `filters`. This allows DataGrid to pass those to each reader so the slicing happens inside the readers and not after. This solves the limitation that was preventing from using the `Connector.query` method from datamesh as explained in the previous comment.

- The `open()` method behaves similarly for most reader types, in that it receives the `xr.Dataset` object from the private method `_open()` (that needs to be overridden), select variables, and applies the filters. For the case of the new `DatasetDatamesh` reader however, the dataset needs to be open with the query information so in that case `open()` is actually overridden. In addition, **the Datamesh reader also needs to know what the coordinates are inside the filters.crop dict** so it can construct the geofilter and the timefilter appropriately. Which explains the change in the `DataGrid` object described below:

### DataGrid

Previously, DataGrid was slicing variables and applying the Filter inside the `DataGrid.ds` property. Now all filtering is handled inside each reader class as explained above and all `DataGrid.ds` do is call the `Dataset.open()` method to return the sliced xr.Dataset object.

More importantly, `DataGrid` must also pass the names of the coordinates along with the variables list and filters for the Datamesh reader to work with `query`. This allows the `geofilter` and `timefilter` to be constructed so `query` can be called. In order to make it more robust and concise and allow coordinates info to be passed around more easily, a new `Coords` pydantic object was defined to replace `lonname` / `latname` / `timename`. `Coords` is defined [here](https://github.com/oceanum/rompy/blob/datamesh/rompy/core/data.py#L27-L32) (we may want to move it to `types` module or some other place if we decide to stick with this approach).

**Review by tomdurrant — APPROVED** [review]
Looks good to me @rafa-guedes

**Comment by rafa-guedes** [comment]
@tomdurrant These last commits implement the changes we have discussed to replace `Dataset` classes by `Source` classes. Now there is `SourceBase` which implements the general api (similar to as previously defined), and subclasses implementing different reading mechanisms such as `SourceOpenDataset`, `SourceDataset`, `SourceIntake` and `SourceDatamesh`. The argument in `DataGrid` which receives one of these objects is now called `source`.

### Some other notable changes:

- `DataBlob` now has one single argument to handle paths, which is also called `source`. It takes an AnyPath type which is validated within pydantic and coerces the appropriate cloudpathlib object (GSPath, PosixPath, etc) depending on how the string looks like.
- `DataGrid` now inherits from `DataBlob` since all parameters in the latter are also defined in the former.
- A few changes made to the `get` methods in both classes above to make them a bit more consistent. They now both take a directory path as input and return a Path object with the name of the output file.
- I have added test files with subsamples of ERA5 wind 10m and gebco. They are 5km resolution and span for 1day, 6-hourly in case of era5 (same period as the ausspec boundary previously available).

**Comment by tomdurrant** [comment]
I might be getting padantic here... but I am not sure I like the new names, particularly SourceOpenDataset. These names refer to the data source, so SourceIntake means the source is an intake catalog, SourceDataset the source is a dataset. SourceOpenDataset sounds like the source is an open dataset, which is easily confused with sourceDataset which represents an open dataset. How about SourceFile? i.e. source dataset from from a file

**Comment by rafa-guedes** [comment]
`How about SourceFile? i.e. source dataset from from a file`

Sounds good!

**Pull request merged**
